/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components

import { CanParameters } from '@casl/ability';

// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface ComponentCustomProperties {
   $can(...args: CanParameters<A>): boolean;
  }
}
